export const hiTechRecipes = {
  button: {
    description: "VSCode-like button",
    className: "ui-button",
    base: {
      minH: "touch",
      minW: "touch",
      px: "4",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "border.default",
      bg: "bg.surface",
      color: "text.primary",
      borderRadius: "none",
      cursor: "pointer",
      fontWeight: "medium",
      transitionProperty: "background-color, border-color, color",
      transitionDuration: "120ms",
      _disabled: {
        cursor: "not-allowed",
        opacity: "0.55",
      },
      _focusVisible: {
        outline: "2px solid token(colors.focus.ring)",
        outlineOffset: "2px",
      },
    },
    variants: {
      variant: {
        solid: {
          bg: "accent.default",
          color: "text.inverse",
          borderColor: "accent.default",
          _hover: { bg: "accent.hover", borderColor: "accent.hover" },
          _active: { bg: "accent.active", borderColor: "accent.active" },
        },
        subtle: {
          bg: "bg.surface",
          color: "text.primary",
          borderColor: "border.default",
          _hover: { bg: "bg.hover", borderColor: "border.strong" },
        },
        danger: {
          bg: "state.error.bg",
          color: "state.error.text",
          borderColor: "state.error.border",
        },
      },
    },
    defaultVariants: {
      variant: "subtle",
    },
  },
  input: {
    className: "ui-input",
    base: {
      minH: "touch",
      px: "4",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "border.default",
      bg: "bg.surface",
      color: "text.primary",
      borderRadius: "none",
      _placeholder: { color: "text.secondary" },
      _focusVisible: {
        outline: "2px solid token(colors.focus.ring)",
        outlineOffset: "2px",
        borderColor: "focus.ring",
      },
    },
  },
  panel: {
    className: "ui-panel",
    base: {
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "border.strong",
      bg: "bg.surface",
      borderRadius: "none",
      p: "4",
    },
  },
  activityItem: {
    className: "ui-activity-item",
    base: {
      w: "100%",
      minH: "touch",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "none",
      color: "icon.default",
      bg: "transparent",
      borderLeftWidth: "2px",
      borderLeftStyle: "solid",
      borderLeftColor: "transparent",
      borderTopWidth: "0",
      borderRightWidth: "0",
      borderBottomWidth: "0",
      _hover: { bg: "bg.hover", color: "icon.active" },
      _focusVisible: {
        outline: "2px solid token(colors.focus.ring)",
        outlineOffset: "-2px",
      },
    },
    variants: {
      active: {
        true: {
          color: "icon.active",
          borderLeftColor: "accent.default",
          bg: "bg.selected",
        },
      },
    },
  },
  sideNavItem: {
    className: "ui-side-nav-item",
    base: {
      w: "100%",
      minH: "touch",
      px: "3",
      display: "inline-flex",
      alignItems: "center",
      gap: "3",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "transparent",
      borderRadius: "none",
      bg: "transparent",
      color: "text.secondary",
      _hover: { bg: "bg.hover", color: "text.primary" },
      _focusVisible: {
        outline: "2px solid token(colors.focus.ring)",
        outlineOffset: "-2px",
      },
    },
    variants: {
      active: {
        true: {
          bg: "bg.selected",
          borderColor: "border.default",
          color: "text.primary",
        },
      },
      collapsed: {
        true: {
          justifyContent: "center",
          px: "0",
        },
      },
    },
  },
  statusBar: {
    className: "ui-status-bar",
    base: {
      h: "statusbar",
      px: "3",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      bg: "bg.statusbar",
      color: "text.inverse",
      borderTopWidth: "1px",
      borderTopStyle: "solid",
      borderTopColor: "border.strong",
      fontSize: "xs",
    },
  },
  panelHeader: {
    className: "ui-panel-header",
    base: {
      mb: "3",
      pb: "2",
      borderBottomWidth: "1px",
      borderBottomStyle: "solid",
      borderBottomColor: "border.default",
      fontSize: "sm",
      fontWeight: "semibold",
      textTransform: "uppercase",
      letterSpacing: "0.04em",
      color: "text.muted",
    },
  },
  toolbarButton: {
    className: "ui-toolbar-button",
    base: {
      minH: "32px",
      minW: "32px",
      px: "2",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "transparent",
      borderRadius: "none",
      bg: "transparent",
      color: "icon.default",
      _hover: {
        bg: "bg.hover",
        borderColor: "border.default",
        color: "icon.active",
      },
      _focusVisible: {
        outline: "2px solid token(colors.focus.ring)",
        outlineOffset: "1px",
      },
    },
  },
  badge: {
    className: "ui-badge",
    base: {
      display: "inline-flex",
      alignItems: "center",
      px: "2",
      py: "1",
      borderWidth: "1px",
      borderStyle: "solid",
      borderRadius: "none",
      textStyle: "xs",
      fontWeight: "medium",
    },
    variants: {
      tone: {
        info: {
          bg: "state.info.bg",
          color: "state.info.text",
          borderColor: "state.info.border",
        },
        success: {
          bg: "state.success.bg",
          color: "state.success.text",
          borderColor: "state.success.border",
        },
        warning: {
          bg: "state.warning.bg",
          color: "state.warning.text",
          borderColor: "state.warning.border",
        },
        error: {
          bg: "state.error.bg",
          color: "state.error.text",
          borderColor: "state.error.border",
        },
      },
    },
    defaultVariants: {
      tone: "info",
    },
  },
} as const;
